window.REVIEW_CONCEPTS=(window.REVIEW_CONCEPTS||[]).concat([
{section:"Ch. 1 — Globalization",term:"Globalization",def:"Growing integration and interdependence among national economies and societies.",aliases:["globalization"],ru:"Глобализация означает усиление взаимосвязей между странами через торговлю, инвестиции, технологии и информацию.",en:"Globalization means increasing cross-border integration through trade, investment, technology, and information."},
{section:"Ch. 1 — Globalization",term:"Globalization of markets",def:"Historically separate national markets becoming increasingly connected.",aliases:["globalization of markets","market globalization"],ru:"Национальные рынки становятся менее изолированными и всё сильнее частью более широкого мирового рынка.",en:"National markets become less isolated and increasingly part of a broader global marketplace."},
{section:"Ch. 1 — Globalization",term:"Globalization of production",def:"Locating productive activities in different countries to benefit from differences in cost or quality.",aliases:["globalization of production","production globalization"],ru:"Компания распределяет производство по странам, используя различия в стоимости, ресурсах и навыках.",en:"A firm spreads production across countries to use differences in cost, resources, and skills."},
{section:"Ch. 1 — Globalization",term:"Outsourcing",def:"Contracting a business activity to an outside supplier or organization.",aliases:["outsourcing"],ru:"Outsourcing означает передачу функции внешнему поставщику; поставщик не обязательно находится за рубежом.",en:"Outsourcing means transferring an activity to an external provider, which does not have to be foreign."},
{section:"Ch. 1 — Globalization",term:"GATT and WTO",def:"GATT preceded the World Trade Organization, which superseded it in the 1990s.",aliases:["gatt and wto","wto","world trade organization"],ru:"Для запоминания: GATT был предшественником WTO; WTO сменил его в 1990-х.",en:"For review: GATT came before the WTO, which superseded it in the 1990s."},
{section:"Ch. 1 — Globalization",term:"International Monetary Fund (IMF)",def:"An institution associated with international monetary stability and balance-of-payments assistance.",aliases:["imf","international monetary fund"],ru:"IMF связан с международной валютно-финансовой стабильностью и помощью странам при проблемах платежного баланса.",en:"The IMF is associated with international monetary stability and support for balance-of-payments problems."},
{section:"Ch. 1 — Globalization",term:"World Bank",def:"An institution associated with long-term development financing and poverty reduction.",aliases:["world bank"],ru:"World Bank в первую очередь связан с долгосрочным развитием и финансированием проектов развития.",en:"The World Bank is primarily associated with long-term development and development financing."},
{section:"Ch. 1 — Globalization",term:"Foreign Direct Investment (FDI)",def:"An investment creating a lasting interest and meaningful influence or control in a foreign operation.",aliases:["fdi","foreign direct investment"],ru:"FDI — прямые инвестиции за рубежом с устойчивым интересом и существенным влиянием или контролем.",en:"FDI is direct investment abroad involving a lasting interest and meaningful influence or control."},
{section:"Ch. 1 — Globalization",term:"FDI flow vs. FDI stock",def:"Flow is investment during a period; stock is the accumulated value at a point in time.",aliases:["fdi flow vs fdi stock","flow vs stock"],ru:"Flow показывает новые инвестиции за период, а stock — накопленный объём на конкретную дату.",en:"Flow measures new investment during a period, while stock measures the accumulated amount at a point in time."},
{section:"Ch. 1 — Globalization",term:"Multinational enterprise (MNE)",def:"A firm that owns or controls productive activities in more than one country.",aliases:["mne","multinational enterprise","mnc"],ru:"MNE владеет или контролирует производственную деятельность более чем в одной стране.",en:"An MNE owns or controls productive activities in more than one country."}
]);