window.REVIEW_CONCEPTS=(window.REVIEW_CONCEPTS||[]).concat([
{section:"Ch. 2 — Political, Economic & Legal Systems",term:"Political economy",def:"The interaction of a country's political, economic, and legal systems.",aliases:["political economy"],ru:"Political economy рассматривает политическую, экономическую и правовую системы вместе, потому что они влияют друг на друга.",en:"Political economy studies political, economic, and legal systems together because they influence one another."},
{section:"Ch. 2 — Political, Economic & Legal Systems",term:"Individualism vs. collectivism",def:"A contrast between prioritizing individual freedom and achievement versus group goals and collective interests.",aliases:["individualism vs collectivism","individualism and collectivism"],ru:"Individualism делает акцент на личности и личной автономии; collectivism — на группе и коллективных целях.",en:"Individualism emphasizes personal autonomy; collectivism gives greater priority to group goals."},
{section:"Ch. 2 — Political, Economic & Legal Systems",term:"Communism vs. social democracy",def:"Traditional communism favors collective or state ownership more strongly, while social democracy works through democratic institutions and a mixed economy.",aliases:["communism vs social democracy","communism and social democracy"],ru:"Communism традиционно даёт государству или коллективу намного большую роль в собственности; social democracy сохраняет демократию и значительный частный сектор.",en:"Traditional communism gives collective or state ownership a much larger role; social democracy preserves democratic institutions and a substantial private sector."},
{section:"Ch. 2 — Political, Economic & Legal Systems",term:"Adam Smith vs. Karl Marx on private property",def:"Smith defended private property and markets; Marx criticized private ownership of the means of production.",aliases:["smith vs marx","adam smith and karl marx"],ru:"Smith связывал частную собственность с экономическими стимулами, а Marx критиковал частную собственность на средства производства.",en:"Smith defended private property as a source of incentives; Marx criticized private ownership of the means of production."},
{section:"Ch. 2 — Political, Economic & Legal Systems",term:"Totalitarianism",def:"A political system in which one person or party exercises broad control and meaningful political opposition is severely restricted.",aliases:["totalitarianism","totalitarian regime"],ru:"Totalitarianism означает сильную концентрацию политической власти и серьёзные ограничения политической конкуренции.",en:"Totalitarianism involves concentrated political power and severe restrictions on political competition."},
{section:"Ch. 2 — Political, Economic & Legal Systems",term:"Market economy",def:"An economic system where supply, demand, prices, and private decisions play the central role in resource allocation.",aliases:["market economy"],ru:"В market economy ресурсы распределяются главным образом через рыночные сигналы, цены и частные решения.",en:"In a market economy, resources are allocated mainly through market signals, prices, and private decisions."},
{section:"Ch. 2 — Political, Economic & Legal Systems",term:"Command economy",def:"An economic system where the state or central planners direct a large share of production and resource allocation.",aliases:["command economy","planned economy"],ru:"В command economy ключевые решения о производстве и распределении ресурсов принимаются государством или центральными плановыми органами.",en:"In a command economy, the state or central planners make major production and allocation decisions."},
{section:"Ch. 2 — Political, Economic & Legal Systems",term:"Mixed economy",def:"An economy combining market mechanisms and private ownership with meaningful government intervention or ownership in some areas.",aliases:["mixed economy"],ru:"Mixed economy сочетает рыночные механизмы и частный сектор с государственной ролью в отдельных сферах.",en:"A mixed economy combines markets and private ownership with government intervention in selected areas."},
{section:"Ch. 2 — Political, Economic & Legal Systems",term:"Common law vs. civil law",def:"Common law relies heavily on precedent and court decisions; civil law relies primarily on systematic written codes.",aliases:["common law vs civil law","common law and civil law"],ru:"Common law сильнее опирается на precedent, а civil law — на кодифицированные письменные нормы.",en:"Common law relies more on precedent; civil law relies more on comprehensive written codes."},
{section:"Ch. 2 — Political, Economic & Legal Systems",term:"Property rights",def:"Legal rights over the use of resources and the income derived from them.",aliases:["property rights"],ru:"Property rights защищают владение и ожидаемую отдачу, поэтому создают стимулы инвестировать.",en:"Property rights protect ownership and expected returns, strengthening incentives to invest."}
]);